on:
  push:
    tags:
      - "*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt install -y --no-install-recommends librime-bin rime-prelude
      - name: Make an archive for distribution
        run: |
          zip -r snow.zip snow_* lua
      - name: Patch
        run: |
          echo -e "patch:\n  schema_list:\n    - { schema: snow_sipin }" > default.custom.yaml
          echo -e "patch:\n  schema/dependencies: [snow_pinyin]\n  engine/translators/@2: null\n  translator/packs: [snow_pinyin.base, snow_pinyin.ext]" > snow_sipin.custom.yaml
          echo -e "patch:\n  schema/dependencies: []\n  translator/packs: [snow_pinyin.base, snow_pinyin.ext]" > snow_pinyin.custom.yaml
      - name: Build
        run: rime_deployer --build . /usr/share/rime-data/
      - name: Make an archive for preview
        run: |
          zip -r snow-build.zip build lua *.txt
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: 冰雪拼音 ${{ github.ref }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
