on:
  push:
    tags:
      - "*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 安装 Rime 输入法用于编译
        run: sudo apt install -y --no-install-recommends librime-bin rime-prelude
      - name: 打包用户安装包
        run: |
          cp rime-stroke/stroke* .
          zip -r snow-pinyin.zip snow_* stroke.* lua
      - name: 写入编译配置
        run: |
          echo -e "patch:\n  schema_list:\n    - { schema: snow_sipin }" > default.custom.yaml
          echo -e "patch:\n  schema/dependencies: [snow_pinyin]\n  engine/translators/@2: null\n  translator/packs: [snow_pinyin.base, snow_pinyin.ext]" > snow_sipin.custom.yaml
          echo -e "patch:\n  schema/dependencies: []\n  translator/packs: [snow_pinyin.base, snow_pinyin.ext]" > snow_pinyin.custom.yaml
      - name: 编译
        run: rime_deployer --build . /usr/share/rime-data/
      - name: 打包预览安装包
        run: |
          zip -r snow-pinyin-build.zip build lua *.txt
      - name: 发布
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 冰雪拼音 ${{ github.ref }}
      - name: 上传
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
