on:
  push:
    tags:
      - "*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install -y --no-install-recommends librime-bin rime-prelude rime-data-stroke
      - name: Patch
        run: |
          echo -e "patch:\n  schema_list:\n    - { schema: snow_sipin }" > default.custom.yaml
      - name: Build
        run: rime_deployer --build . /usr/share/rime-data/
      - name: Make an archive
        run: |
          zip -r snow.zip snow_* lua
          zip -r snow-build.zip build lua *.txt
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: 冰雪拼音 ${{ github.ref }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
